// Shared Electron IPC channel names.

/** Shared IPC channel names. */
export const ipcChannels = {
  applyNetworkSettings: 'dune:runtime:apply-network-settings',
  cancelTelegramSetupSession: 'dune:runtime:cancel-telegram-setup-session',
  copyText: 'dune:runtime:copy-text',
  createAgent: 'dune:runtime:create-agent',
  deleteLocalData: 'dune:runtime:delete-local-data',
  deleteAgent: 'dune:runtime:delete-agent',
  clearNotificationHistory: 'dune:notifications:clear-history',
  ensureProjectArtifactFolder: 'dune:runtime:ensure-project-artifact-folder',
  ensureProjectMainAgent: 'dune:runtime:ensure-project-main-agent',
  getAgentTranscriptPage: 'dune:runtime:get-agent-transcript-page',
  getNotificationHistory: 'dune:notifications:get-history',
  getNotificationSettings: 'dune:notifications:get-settings',
  getProjectActivityPage: 'dune:workflow:get-project-activity-page',
  getRuntimeSnapshot: 'dune:runtime:get-snapshot',
  getTelegramSetupSession: 'dune:runtime:get-telegram-setup-session',
  listProjectArtifactEntries: 'dune:runtime:list-project-artifact-entries',
  openExternal: 'dune:runtime:open-external',
  openPath: 'dune:runtime:open-path',
  prepareProjectRootPath: 'dune:runtime:prepare-project-root-path',
  reloadExternalChannels: 'dune:runtime:reload-external-channels',
  resetRuntime: 'dune:runtime:reset',
  restartApp: 'dune:runtime:restart-app',
  runIsolatedResearch: 'dune:runtime:run-isolated-research',
  runtimeSnapshotUpdated: 'dune:runtime:snapshot-updated',
  itemActivityUpdated: 'dune:workflow:item-activity-updated',
  selectAgent: 'dune:runtime:select-agent',
  sendAgentMessage: 'dune:runtime:send-agent-message',
  startTelegramSetupSession: 'dune:runtime:start-telegram-setup-session',
  selectProjectDirectory: 'dune:runtime:select-project-directory',
  updateAgentChannel: 'dune:runtime:update-agent-channel',
  updateAgentDefinition: 'dune:runtime:update-agent-definition',
  workflowChanged: 'dune:runtime:workflow-changed',
  storageDelete: 'dune:storage:delete',
  storageGet: 'dune:storage:get',
  storageKeys: 'dune:storage:keys',
  storageSet: 'dune:storage:set',
  updateNotificationSettings: 'dune:notifications:update-settings',
} as const;
