export const ipcChannels = {
  applyNetworkSettings: 'dune:runtime:apply-network-settings',
  copyText: 'dune:runtime:copy-text',
  createAgent: 'dune:runtime:create-agent',
  deleteAgent: 'dune:runtime:delete-agent',
  getRuntimeSnapshot: 'dune:runtime:get-snapshot',
  openExternal: 'dune:runtime:open-external',
  reloadExternalChannels: 'dune:runtime:reload-external-channels',
  resetRuntime: 'dune:runtime:reset',
  restartApp: 'dune:runtime:restart-app',
  runtimeSnapshotUpdated: 'dune:runtime:snapshot-updated',
  selectAgent: 'dune:runtime:select-agent',
  sendAgentMessage: 'dune:runtime:send-agent-message',
  storageDelete: 'dune:storage:delete',
  storageGet: 'dune:storage:get',
  storageKeys: 'dune:storage:keys',
  storageSet: 'dune:storage:set',
} as const;
